name: Apply Terraform

on:
  push:
    branches:
      - master

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory to backend
        run: |
          cd backend
          ls
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-2
      - name: Set environment variables
        run: |
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> terraform.tfvars
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> terraform.tfvars
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> terraform.tfvars
          ls
      - name: Initialize Terraform
        run: |
          ls
          terraform init
      - name: Apply Terraform
        run: |
          ls
          terraform apply -var-file=terraform.tfvars
